# Numpy

## Array Mathematics


In [1]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print(a + b)                     #[  6.   8.  10.  12.]
print(numpy.add(a, b))          #[  6.   8.  10.  12.]

print(a - b)                     #[-4. -4. -4. -4.]
print(numpy.subtract(a, b))      #[-4. -4. -4. -4.]

print(a * b)                     #[  5.  12.  21.  32.]
print(numpy.multiply(a, b))      #[  5.  12.  21.  32.]

print(a / b)                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print(numpy.divide(a, b))        #[ 0.2         0.33333333  0.42857143  0.5       ]

print(a % b)                     #[ 1.  2.  3.  4.]
print(numpy.mod(a, b))           #[ 1.  2.  3.  4.]

print(a**b)                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print(numpy.power(a, b))         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [44]:
import numpy 

n, m = map(int, input().split())

a = numpy.array([list(map(int, input().split())) for i in range(n)])
b = numpy.array([list(map(int, input().split())) for i in range(n)])

print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(numpy.floor_divide(a, b))
print(numpy.mod(a, b))
print(numpy.power(a, b))

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [48]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [49]:
print(numpy.floor(my_array))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [50]:
print(numpy.ceil(my_array))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [51]:
print(numpy.rint(my_array))

[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [72]:
import numpy

a = numpy.array(list(map(float, input().split())))
numpy.set_printoptions(legacy='1.13')

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [74]:
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print(my_array)
print(numpy.sum(my_array, axis=0))
print(numpy.sum(my_array, axis=1))
print(numpy.sum(my_array, axis=None))
print(numpy.sum(my_array))

[[1 2]
 [3 4]]
[4 6]
[3 7]
10
10


In [75]:
print(numpy.prod(my_array, axis=0))
print(numpy.prod(my_array, axis=1))
print(numpy.prod(my_array, axis=None))
print(numpy.prod(my_array))

[3 8]
[ 2 12]
24
24


In [97]:
import numpy

n, m = map(int, input().split())

a = numpy.array([list(map(int, input().split())) for i in range(n)])

print(numpy.prod(numpy.sum(a,axis=0)))

 2 2
 1 2
 3 2


16


## Inner and Outer

In [98]:
import numpy

A = numpy.array([0, 1])
B = numpy.array([3, 4])

print(numpy.inner(A, B))

4


In [99]:
print(numpy.outer(A, B))

[[0 0]
 [3 4]]


In [100]:
import numpy

a = numpy.array(list(map(int, input().split())))
b = numpy.array(list(map(int, input().split())))

print(numpy.inner(a, b))
print(numpy.outer(a, b))

 0 1
 2 3


3
[[0 0]
 [2 3]]


## Polynominas

In [103]:
print(numpy.poly([-1, 1, 1, 10]))

# (x+1)(x-1)(x-1)(x-10)=0 となる係数を探す -> p(x) = 1*x^4-11*x^3+9*x^2+11*x-10

[  1. -11.   9.  11. -10.]


In [102]:
print(numpy.roots([1, 0, -1]))

# 1*x^3+0*x^2-1*x=0となるxを探す -> x(x+1)(x-1)=0 

[-1.  1.]


In [105]:
print(numpy.polyint([1, 1, 1]))

# p(x)=1*x^3+1*x^2+1*xを積分した時の係数,デフォルトは積分定数Cは0

[ 0.33333333  0.5         1.          0.        ]


In [107]:
print(numpy.polyder([1, 1, 1, 1]))

# p(x)=1*x^3+1*x^2+1*x+1を微分した時の係数

[3 2 1]


In [109]:
print(numpy.polyval([1, -2, 0, 2], 4))

# 係数 [1, -2, 0, 2] は p(x) = 1x^3-2x^2+4 に対応、　この多項式をx=4で評価

34


In [113]:
import numpy

coefficients = numpy.array(list(map(float,input().split())))

x = int(input())

print(numpy.polyval(coefficients, x))

 1.1 2 3
 0


3.0


## Linear Algebra

In [118]:
print(numpy.linalg.det([[1 , 2], [2, 1]]))
# 1*1 - 2*2 (a11*a22-a12*a21)
# 行列式

-3.0


In [117]:
vals, vecs = numpy.linalg.eig([[1, 2], [2, 1]])
print(vals)
print(vecs

# 固有値と固有ベクトル

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [119]:
print(numpy.linalg.inv([[1, 2], [2, 1]]))

# 逆行列

[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]


In [125]:
n = int(input())

a = numpy.array([list(map(float, input().split())) for i in range(n)])
print(round(numpy.linalg.det(a), 2))

 2
 1.1 1.1
 1.1 1.2


0.11


## Concatenate

In [2]:
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

print(numpy.concatenate((array_1, array_2, array_3)))

[1 2 3 4 5 6 7 8 9]


In [3]:
array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print(numpy.concatenate((array_1, array_2), axis=1))

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [7]:
n, m, p = map(int, input().split())

arrays = numpy.array([list(map(int, input().split())) for _ in range(n+m)])

print(arrays)

 4 3 2
 1 2
 1 2
 1 2
 1 2
 3 4
 3 4
 3 4


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [8]:
print(numpy.zeros((1,2)))

[[0. 0.]]


In [10]:
print(numpy.zeros((1,2), dtype=numpy.int))

[[0 0]]


/var/folders/fj/rf2znhjj53z6lgms_bsqgt740000gn/T/ipykernel_63340/3425974107.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.zeros((1,2), dtype=numpy.int))


In [11]:
print(numpy.ones((1,2)))

[[1. 1.]]


In [12]:
print(numpy.ones((1,2), dtype=numpy.int))

[[1 1]]


/var/folders/fj/rf2znhjj53z6lgms_bsqgt740000gn/T/ipykernel_63340/3502782573.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.ones((1,2), dtype=numpy.int))


In [1]:
import numpy

shape = list(map(int, input().split()))
print(numpy.zeros(shape, dtype=int))
print(numpy.ones(shape, dtype=int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


/var/folders/fj/rf2znhjj53z6lgms_bsqgt740000gn/T/ipykernel_64283/1421512430.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.zeros(shape, dtype=numpy.int))
/var/folders/fj/rf2znhjj53z6lgms_bsqgt740000gn/T/ipykernel_64283/1421512430.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review you

## Eye and Identity

In [2]:
print(numpy.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
print(numpy.eye(8,7,k=1))

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [5]:
print(numpy.eye(8,7,k=-2))

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]


In [7]:
print(numpy.eye(8,7))

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [8]:
import numpy
numpy.set_printoptions(legacy='1.13')

n, m = map(int, input().split())

print(numpy.eye(n,m))

 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
